#!/bin/python3

# predefined modules
from termcolor import colored
from flask import Flask,render_template,request,jsonify,request,session
from flask_ngrok import run_with_ngrok
from werkzeug.datastructures import FileStorage

import sqlite3 as sql
# created modules
from static.modules.basic import *
# from static.modules.forensics import *
from static.modules.pentest import *
from static.modules.packages import *
from static.modules.wifi import *

# CLASSES

# Main class
class ROUTER:
    def __init__(self):
        self.wrun,self.prun,self.frun,self.wifi=True,True,True,{}
        self.SSID=''
        self.BSSID=''
        self.IP='192.168.28.1'
        self.drange='192.168.28.30'
        self.dtime='24'
        self.PASSWD=''
        self.BASEDIR=['/root/']
        self.result={}
        self.mail=""
        self.passwd=""
        self.BS=BASIC()
        self.num=1
        self.lp='static/logs/info/'
        self.pp='static/logs/evidence/'
        self.url=[]
        self.clients=[]
        self.ipath=defaultdict(list)
        self.ppath=defaultdict(list)
        self.clients=open('static/APconf/accept','r').readlines()

    def pinit(self):
        self.SC=SCANNER()
        self.SC.iscan()
        # wifi scanner
        print(colored('[i] information, [+] process information, [*] warning, [-] error','blue'))
        sleep(0.5)
        print(colored('[i] press CTRL+C for quit','blue'))
        sleep(0.5)
        print(colored('[+] Selecting interface','blue'))
        sleep(0.5)
        self.network,self.interface,self.run=self.SC.iface[0],[self.SC.iface[1],self.SC.iface[2]],self.SC.iface[3]
        print(colored('[+] Selected interfaces : ','blue'),colored(self.network+' '+str(self.interface),'green'))
        sleep(0.5)
        self.WF=WIFI(self.interface[1])
        self.AP=AP(self.interface[0],self.network,self.drange,self.dtime)
        self.athread=Thread(target=self.AP.start,args=(self.SSID,self.PASSWD,))
        self.athread.start()
        self.BSSID=psutil.net_if_addrs()[self.interface[0]][1].address
        # self.DF=DFORENSICS(self.network,self.clients,self.BSSID)
        sleep(0.5)
        self.w=Thread(target=self.wstart)
        self.p=Thread(target=self.pstart)
        self.f=Thread(target=self.fstart)
        # Enable monitor mode
        os.system('ifconfig '+self.interface[1]+' down')
        os.system('iwconfig '+self.interface[1]+' mode monitor')
        os.system('ifconfig '+self.interface[1]+' up')
        print(colored('[+] Monitor mode enabled in ','blue'),colored(self.interface,'green'))
        sleep(0.5)
        subprocess.Popen("qterminal -e './static/source/ngrok start -all'",shell=True)
        self.url=self.BS.msend(self.mail,self.passwd)
        cont=open('static/modules/fileanalysis.py','r').readlines()
        cont[-1]="HACKIN('"+self.url[0]+"')"
        open('static/modules/fileanalysis.py','w').write(''.join(cont))


    def start(self):
        try:
            self.BS.rdesk()
            self.w.start()
            self.p.start()
            self.f.start()
        except Exception as e:
            print(e)
            self.stop()

    def wstart(self):
        try:
            while self.wrun:
                wthread=Thread(target=self.WF.start)
                wthread.start()
                while wthread.is_alive(): pass
                self.result[1]=copy.copy([self.WF.info,self.SC.detail])
                print(self.result)
        except Exception as e: pass

    def pstart(self):
        try:
            while self.prun:
                cthread=Thread(target=self.SC.pscan,args=(self.IP,self.BSSID,))
                cthread.start()
                while cthread.is_alive(): pass
                self.result[2]=copy.copy(self.SC.result)
        except Exception as e: pass

    def fstart(self):
        cont=open('static/modules/forensics.py','r').readlines()
        cont[-1]="DFORENSICS('"+self.network+"',"+str(self.clients)+",'"+self.BSSID+"',"+str(self.num)+").pmstart()"
        open('static/modules/forensics.py','w').write(''.join(cont))
        self.DF=subprocess.Popen('python3.6 static/modules/forensics.py',shell=True)
        while self.DF.poll() is None:
            sleep(5)
            for p,d,ff in os.walk(self.lp):
                for f in ff:
                    self.ipath[f]=[os.path.join(p,f).replace('/','|'),None]
            for p,d,ff in os.walk(self.pp):
                for f in ff:
                    self.ppath[f]=[os.path.join(p,f).replace('/','|'),None]
            self.result[3]=copy.copy([self.ipath,self.ppath])

    def stop(self):
        self.wstop()
        self.pstop()
        self.fstop()
        #Disable monitor mode
        os.system('ifconfig '+self.interface[1]+' down')
        os.system('iwconfig '+self.interface[1]+' mode managed')
        os.system('ifconfig '+self.interface[1]+' up')
        print(colored('[+] Monitor mode disabled in ','blue'),colored(self.interface,'green'))

    def wstop(self):
        self.WF.run=False
        main.wrun=False
        if main.w.is_alive(): main.w.join()

    def pstop(self):
        main.prun=False
        if main.p.is_alive(): main.p.join()

    def fstop(self):
        main.frun=False
        if main.f.is_alive(): main.f.join()

    def config(self,ip,mac):
        answered=srp(Ether(dst='ff:ff:ff:ff:ff:ff')/ARP(pdst=self.interfaces[self.iface[1]][1]),iface=self.iface[1],timeout=1,verbose=False)[0]
        for i, ans in enumerate(answered):
            self.clients[i]=[ans[1].psrc,ans[1].hwsrc]
            open('static/APconf/accept','a').write(ans[1].hwsrc+'\n')
        self.clients=open('static/APconf/accept','r').readlines()

app=Flask(__name__)

@app.route('/',methods=['POST','GET'])
def index():
    session['admin']=None
    if request.method=='POST':
        con=sql.connect('static/source/database.db')
        cur=con.cursor()
        userid=request.form['userid']
        passwd=request.form['passwd']
        cur.execute('select count(*) from login where name="'+userid+'" and password="'+passwd+'";')
        if cur.fetchall()[0][0] == 1:
            session['admin']=userid
            return render_template('monitor.html')
        else: return render_template('index.html',warning='invalid user ID or password')
    else: return render_template('index.html',warning='')

@app.route('/monitor/')
def monitor():
    if session['admin'] is not None: return jsonify(main.result)
    else: return jsonify('Unauthorized access')

@app.route('/fileview/<fname>')
def fileview(fname):
    cont=[]
    print(fname.replace('|','/'))
    if session['admin'] is not None:
        with open(fname.replace('|','/'),'r') as fp:
            cont=fp.readlines()
        return jsonify(cont[(len(cont)-52):-1])
    else: return jsonify('Unauthorized access')

@app.route('/upload/<fname>',methods=['POST'])
def upload(fname):
    try:
        FileStorage(request.stream).save('static/logs/system/'+fname)
        # open('static/logs/system/'+fname,'w+').write(request.files)
        return jsonify('filesaved to the server and system')
    except:return jsonify('Something went wrong')

@app.route('/start/<option>')
def start(option):
    if session['admin'] is not None:
        if option == 'all': main.start()
        elif option == 'wifi': main.wstart()
        elif option == 'pentest': main.pstart()
        elif option == 'forensic': main.fstart()
        elif option == 'rdesk': main.BS.rdesk()
    else: return jsonify('Unauthorized access')

@app.route('/stop/<option>')
def stop(option):
    if session['admin'] is not None:
        if option == 'all': main.stop()
        elif option == 'wifi': main.wstop()
        elif option == 'pentest': main.pstop()
        elif option == 'forensic': main.fstop()
    else: return jsonify('Unauthorized access')

if __name__=='__main__':
    main=ROUTER()
    main.pinit()
    Thread(target=main.start).start()
    app.secret_key = os.urandom(42)
    # app.debug=True
    app.run()