#!/bin/bash

# Python version 3.6.9 installation

# wget https://www.python.org/ftp/python/3.6.9/Python-3.6.9.tar.xz

# tar -xvf Python-3.6.9.tar.xz

# cd Python-3.6.9/

# ./configure

# make

# make install

# pip3 Requirements packeages

pip3 install NetfilterQueue

pip3 install threaded

pip3 install scapy

pip3 install python3-nmap

pip3 install psutil

pip3 install scikit-learn

pip3 install termcolor

pip3 install Flask

pip3 install flask-ngrok

pip3 install pandas

pip3 install sets

pip3 install scrapy

pip3 install selenium

pip3 install phonenumbers

pip3 install spacy

python3 -m spacy download en

sudo apt-get install -y hostapd dnsmasq novnc x11vnc

echo "authtoken: 1iwPCBah3nttCu9jlowu3a609CT_6NSquxiFCvWZjt8zm1fUi

tunnels:
  rdesk:
    proto: http
    addr: 8081
  admin:
    proto: http
    addr: 5000
" > /root/.ngrok2/ngrok.yml